version: '3'

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:
